### ISSUE TITLE
'event' without 'segment'

### ISSUE THREAD

**Issue by ruoshiliu** [SDOlivia/FineGym#1]
Hi,

Thank you for sharing the features and dataset and congrats on the acceptance of the CVPR paper. Looking at the 'temporal annotation' file of the dataset, I notice there are a lot of events with no segments. Since there are 530 subactions in the category file which doesn't include those event, I'm wondering what's the purpose of those labels? Are they events without subactions? Or are those just unlabeled?

**Comment by zhaoyue-zephyrus** [comment]
Hi,

You are probably referring to the men's events which do NOT have sub-action annotations. We used all these events for the event-level recognition in the paper's Table 2.

**Comment by Finspire13** [comment]
Hi, thanks for your dataset and there is a follow-up question.

Do you have any plan to further annotate these unlabelled events in the next version of the dataset?
