### ISSUE TITLE
Some Videos are not available in TouTube

### ISSUE THREAD

**Issue by xxtars** [SDOlivia/FineGym#11]
> [["0LtLS9wROrk", true, "Downloaded"], ["0MtilFKz4cA", false, "Fail"], ["0jqn1vxdhls", true, "Downloaded"], ["0l9BgyraB34", true, "Downloaded"], ["1Fdwuy2V9EY", true, "Downloaded"], ["1JsRXIoR3C0", true, "Downloaded"], ["1_Jqkqc9TgE", false, "Fail"], ["1assNNJTETs", true, "Downloaded"], ["1iXEcpie_HY", true, "Downloaded"], ["1rkcLEAMTpw", true, "Downloaded"], ["1sPWceVH4e8", true, "Downloaded"], ["26Y8BsNiiL8", true, "Downloaded"], ["2AGztyrY25g", true, "Downloaded"], ["2Qw1e4-nWrk", true, "Downloaded"], ["2giTb7IpJDU", true, "Downloaded"], ["2pBxfMAIaXY", true, "Downloaded"], ["3AsaRnTEVyA", true, "Downloaded"], ["3PywNMDCvNQ", true, "Downloaded"], ["3hD6S3NFaUU", true, "Downloaded"], ["4kG0jbeQ70g", false, "Fail"], ["4mzbybgzoJo", true, "Downloaded"], ["4nJVgH7_pZU", true, "Downloaded"], ["5BTXyq9Y5-M", true, "Downloaded"], ["5Bfx6Wz3KKs", true, "Downloaded"], ["5X85zLeLmks", true, "Downloaded"], ["5cuxEEKyth8", true, "Downloaded"], ["6DU7z7yhyR8", true, "Downloaded"], ["6W0HCqIgm6Y", true, "Downloaded"], ["6_ATNiI0y-E", true, "Downloaded"], ["6fqDZHFr2yo", true, "Downloaded"], ["772GdSBMD9U", true, "Downloaded"], ["7NNhxZ7wRb4", true, "Downloaded"], ["8N3CBVAft40", true, "Downloaded"], ["8SOPENz_OJM", true, "Downloaded"], ["8WGrvkd6ZEU", true, "Downloaded"], ["8YSDFKGwP4U", true, "Downloaded"], ["8hdc_j3Et4Y", true, "Downloaded"], ["8jfPAvqYAs8", true, "Downloaded"], ["8ojzu5TJzXU", true, "Downloaded"], ["8tdGvTDHmzc", true, "Downloaded"], ["9Mtbac7g15I", true, "Downloaded"], ["9kMJBZj0Aaw", true, "Downloaded"], ["A0xAXXysHUo", true, "Downloaded"], ["AZ4wWG6Rcak", true, "Downloaded"], ["AfPO3koqlXQ", true, "Downloaded"], ["AzC4zqzkP-8", true, "Downloaded"], ["B0f3RF6jEjI", true, "Downloaded"], ["BBxvSeyK_7s", true, "Downloaded"], ["BLzs5opw8uM", true, "Downloaded"], ["BQhX6F3gpp8", true, "Downloaded"], ["C5Yfd1IWjmM", true, "Downloaded"], ["C85Z3_K7Vbg", true, "Downloaded"], ["CUuRl0Bwbbc", true, "Downloaded"], ["Cdyc4A4b6x8", true, "Downloaded"], ["Ce7b8VmmzdA", true, "Downloaded"], ["CgoVY405LeE", true, "Downloaded"], ["CkNz9ZIQmZI", true, "Downloaded"], ["DA4zEN7oCM4", true, "Downloaded"], ["DG7upbhB1bI", true, "Downloaded"], ["DTedv-hhHU4", true, "Downloaded"], ["Dle5b89atuU", true, "Downloaded"], ["DyZ2qj6x1UE", true, "Downloaded"], ["E-1hTCGUCts", false, "Fail"], ["E3AHJ6-QS8M", true, "Downloaded"], ["ECz4TOftHYQ", true, "Downloaded"], ["EFvDqOF1sCk", true, "Downloaded"], ["EKb2MMJSoeI", true, "Downloaded"], ["EizeIkrDtQk", true, "Downloaded"], ["FEWTGYiWEaQ", true, "Downloaded"], ["FNEeMvHmuEw", true, "Downloaded"], ["Fv_MFMVsHbU", true, "Downloaded"], ["GCyW1jPfWdg", false, "Fail"], ["GEjRXo8Dvwc", true, "Downloaded"], ["GF8D7Dx2mhs", true, "Downloaded"], ["GP8v5l33P_k", true, "Downloaded"], ["GbUQwE9N3aM", true, "Downloaded"], ["GgzyQvfpyTk", true, "Downloaded"], ["Gng3ezTNGog", true, "Downloaded"], ["Gv53p8QE6bM", false, "Fail"], ["HJeID2Gf0zU", true, "Downloaded"], ["HuD-oRJdhMQ", true, "Downloaded"], ["HubzmiNVVXs", true, "Downloaded"], ["Hx86Nf2oPMI", false, "Fail"], ["HyyVf-Z_rRs", true, "Downloaded"], ["I1OMnMSk1Lg", true, "Downloaded"], ["I749IS2IeFY", true, "Downloaded"], ["ICL5k84viw0", true, "Downloaded"], ["IP96HTdCvWs", true, "Downloaded"], ["IQblfc_nLKY", false, "Fail"], ["IWFgo-tEEs8", true, "Downloaded"], ["IZy40LwRdbM", true, "Downloaded"], ["ItBRb9LB-VI", true, "Downloaded"], ["JGlyJWNXhQ0", true, "Downloaded"], ["JHqcbeKepSg", true, "Downloaded"], ["JfIlDssMeGc", true, "Downloaded"], ["KDjuRG3-Xf0", true, "Downloaded"], ["LHZAh32EoC8", true, "Downloaded"], ["LdPvjfSDBcQ", true, "Downloaded"], ["Lt0HnPxdzHw", true, "Downloaded"], ["M84bx4-yqxs", true, "Downloaded"], ["MDxIRDDWw1w", true, "Downloaded"], ["MVLZz2J6tcE", true, "Downloaded"], ["MlEq-nh1cCw", true, "Downloaded"], ["MoBr1cguTY4", false, "Fail"], ["MyrqGZXxpsY", true, "Downloaded"], ["Ny0ZMOIyb9M", true, "Downloaded"], ["Ny428AbVReU", false, "Fail"], ["O4pSYZNFej0", true, "Downloaded"], ["OB_lo-GVUxY", true, "Downloaded"], ["OC43_IZUE6A", true, "Downloaded"], ["OGK3TCz71_I", true, "Downloaded"], ["OIJe8fQw7Wo", true, "Downloaded"], ["OO5T_74tdkM", true, "Downloaded"], ["P31Ht3H76ok", true, "Downloaded"], ["POZkrxioEus", false, "Fail"], ["PZHRQtq_P8I", true, "Downloaded"], ["PaVNLvldLeI", true, "Downloaded"], ["PgNRyuavbS4", true, "Downloaded"], ["QCDks6aiWfs", false, "Fail"], ["QO6SYIJ_Vpk", true, "Downloaded"], ["QUJRNcPXxY8", true, "Downloaded"], ["QUzsdG7jyj0", false, "Fail"], ["Q_-ffElHJbo", true, "Downloaded"], ["R5hsatlgi70", false, "Fail"], ["R9XUGR-VlTg", true, "Downloaded"], ["RLDjrhjikT4", true, "Downloaded"], ["RjpOEHmTf7I", true, "Downloaded"], ["Ry5PFp-pRmA", true, "Downloaded"], ["S0_UALsRaa8", true, "Downloaded"], ["SY79Budr1_0", true, "Downloaded"], ["SmM5COoXqDA", false, "Fail"], ["TBsWos4T4OE", true, "Downloaded"], ["TCiufCzMtDs", true, "Downloaded"], ["TILXmEWGxeI", true, "Downloaded"], ["TXpgPT5Jdiw", true, "Downloaded"], ["TjSBQd2CGYU", true, "Downloaded"], ["U3ww8htiEIU", true, "Downloaded"], ["UcCTusldh6w", true, "Downloaded"], ["Uo7ubem-G9I", true, "Downloaded"], ["UpillmEXgY8", true, "Downloaded"], ["UyGu-WTodV0", false, "Fail"], ["VWsVUnoyUoA", true, "Downloaded"], ["Vq-w0Jk7y7g", true, "Downloaded"], ["VuaiQO1Hio4", false, "Fail"], ["WCcSXjsCVMA", true, "Downloaded"], ["WGsCzfWF-4w", true, "Downloaded"], ["Wu1gxxpbF2o", true, "Downloaded"], ["WuDs9FMmbvg", true, "Downloaded"], ["X4CY5MZwI9I", true, "Downloaded"], ["X4ajWw8L19s", true, "Downloaded"], ["X6sggzI0mw8", true, "Downloaded"], ["XL8N3BEWdho", false, "Fail"], ["XSotH7d2tBs", true, "Downloaded"], ["XZak6ktC90c", true, "Downloaded"], ["Xqra-PqzhD4", true, "Downloaded"], ["Xw1UvouxVLk", true, "Downloaded"], ["XyOiHmWWFJo", true, "Downloaded"], ["YUKvzPL5nok", true, "Downloaded"], ["YesOPAkCA40", true, "Downloaded"], ["YlHAYGx_1XY", true, "Downloaded"], ["YqVDhFXPdHk", true, "Downloaded"], ["Z0bBRwAzKe0", true, "Downloaded"], ["Z2T9B4qExzk", true, "Downloaded"], ["Z35DUnhNyJ4", false, "Fail"], ["Z5X3Cl9qDcg", true, "Downloaded"], ["ZHpME-SbKdQ", true, "Downloaded"], ["ZhRbeozHhvM", true, "Downloaded"], ["_E21jlKax8M", true, "Downloaded"], ["_P9yn7lkMYI", true, "Downloaded"], ["_WRXODwruTg", false, "Fail"], ["_aqdgFWnjr0", false, "Fail"], ["_hr_uPaN_kU", true, "Downloaded"], ["_z3-NBUlEpU", true, "Downloaded"], ["aEZbP-Yephw", true, "Downloaded"], ["aN3PC4tJokk", true, "Downloaded"], ["aN9hSsP6xTg", true, "Downloaded"], ["aQy3nHo3V0E", false, "Fail"], ["auJQn8itbUo", true, "Downloaded"], ["bCDJ9CUBvqs", true, "Downloaded"], ["b_NXpFUz1mQ", true, "Downloaded"], ["bhlCsgZA-dI", true, "Downloaded"], ["cFliG52xX3E", true, "Downloaded"], ["cSh74jSRht8", true, "Downloaded"], ["cWztehyIFkg", true, "Downloaded"], ["dqUNtY2GwW4", true, "Downloaded"], ["e3EsDlpNo0c", true, "Downloaded"], ["eH-ZgOT8ASM", true, "Downloaded"], ["eH7ZrqLY_D0", true, "Downloaded"], ["eallFwiLHwM", false, "Fail"], ["eeAuiqP_WoM", true, "Downloaded"], ["esQQbBhuXbM", true, "Downloaded"], ["etopgnZ5dZM", true, "Downloaded"], ["f-1FbFegbuQ", true, "Downloaded"], ["f4PNWx4CqSo", true, "Downloaded"], ["f6k7PBGgeb4", true, "Downloaded"], ["fDa0HpoXES4", true, "Downloaded"], ["fH-VYYl9elA", true, "Downloaded"], ["gDmmqalpisc", true, "Downloaded"], ["gMNCwgXtQIw", true, "Downloaded"], ["gPDLiStPylg", true, "Downloaded"], ["gRgndu5MZY4", true, "Downloaded"], ["gYyLkUbGuUU", true, "Downloaded"], ["gZ3vBnIClWo", true, "Downloaded"], ["hMeTZBe6UBk", false, "Fail"], ["hibW8s4WQmQ", true, "Downloaded"], ["hmHwFuvodg0", false, "Fail"], ["hp2PJMAJqyA", true, "Downloaded"], ["i87qMWsFbEI", true, "Downloaded"], ["iED7dfzHOQg", true, "Downloaded"], ["iSQqsVFkQAA", false, "Fail"], ["j3mdoE28v_w", true, "Downloaded"], ["jABvTCCWinA", true, "Downloaded"], ["jR0OFsCYcD4", false, "Fail"], ["jWgswqLdPFA", false, "Fail"], ["jfUEdIB1qtk", true, "Downloaded"], ["ji4smBYYANs", true, "Downloaded"], ["jpi6ajdMTp4", true, "Downloaded"], ["jxCmesIj6gw", true, "Downloaded"], ["jz594oTnl-k", true, "Downloaded"], ["k8zhOvRBjGo", true, "Downloaded"], ["k9MYHxUyn60", true, "Downloaded"], ["knIaoNcydck", false, "Fail"], ["l-ctNiOuCBc", true, "Downloaded"], ["lC-eV2NSjd0", true, "Downloaded"], ["lDhO-YBranc", true, "Downloaded"], ["laDLJBvycZA", true, "Downloaded"], ["lkzdrs5B_3Q", true, "Downloaded"], ["lqxmTxsc0b0", true, "Downloaded"], ["lrwiYiFGQZE", true, "Downloaded"], ["mGOi2H_NKig", true, "Downloaded"], ["mI7pLIDnTiQ", true, "Downloaded"], ["mQ59PLtU4QA", true, "Downloaded"], ["mgtMKd072Pg", true, "Downloaded"], ["muC0SnMSlyQ", true, "Downloaded"], ["n9-yxVGYMRw", true, "Downloaded"], ["nEoD3t5O3Hg", true, "Downloaded"], ["nSDRagdrJ-A", true, "Downloaded"], ["nZN71JnWjsk", true, "Downloaded"], ["o9XA7bVfTAg", true, "Downloaded"], ["oP13FE74rOg", false, "Fail"], ["oShVYr-GRqw", true, "Downloaded"], ["oTDPlGMRGrc", true, "Downloaded"], ["o_jYRSPjtdw", true, "Downloaded"], ["om-qKQXxnH4", true, "Downloaded"], ["owZ2Fv4Li8M", true, "Downloaded"], ["p42w02g4Ce4", true, "Downloaded"], ["pDymfQS91xI", true, "Downloaded"], ["pEoWudMTZbY", true, "Downloaded"], ["pXEay_iiG90", true, "Downloaded"], ["peUK8cBOksg", false, "Fail"], ["pkeU_NPi53w", true, "Downloaded"], ["q3kjkmjtTBk", false, "Fail"], ["qBlozVQ7NOc", true, "Downloaded"], ["qGvIwgHzCH8", true, "Downloaded"], ["qfBalcxF8JY", false, "Fail"], ["qfgrzomg0nc", true, "Downloaded"], ["qzi2cKZCf94", true, "Downloaded"], ["rDGtaRN_eyc", true, "Downloaded"], ["rciejFbZ38s", true, "Downloaded"], ["rkdtpVqemb4", true, "Downloaded"], ["rrrgsW--AE8", true, "Downloaded"], ["s7pyZPf6fKU", true, "Downloaded"], ["sEgELazFtxQ", false, "Fail"], ["sQHqtXaO2Dc", true, "Downloaded"], ["t4zYCqrCvXA", false, "Fail"], ["t7Xgg9bejOM", true, "Downloaded"], ["tQLr-oGPO_I", true, "Downloaded"], ["tjf2ZWcrs1w", true, "Downloaded"], ["tuApuPd_pqA", true, "Downloaded"], ["u6tU91r1Szo", true, "Downloaded"], ["uDZVn-K4GE4", true, "Downloaded"], ["ucb1zZ6I1Ks", true, "Downloaded"], ["upaJ16I0zmQ", true, "Downloaded"], ["v-ZCEj9Io_w", true, "Downloaded"], ["v3mISBmwrUM", true, "Downloaded"], ["v601eVMn9f0", true, "Downloaded"], ["v8mUSyDkVjQ", false, "Fail"], ["vMn2UWFmMDY", true, "Downloaded"], ["vNiZ8qWXDe4", true, "Downloaded"], ["vY-jPM995Gk", true, "Downloaded"], ["vf7ga_HUVF8", true, "Downloaded"], ["wWZry3-5sF0", true, "Downloaded"], ["wWwc2BbO598", true, "Downloaded"], ["wYbfwx93VXk", true, "Downloaded"], ["wi_LXsy4kig", true, "Downloaded"], ["wmOIRMcB93U", false, "Fail"], ["wolPuHKrX9o", true, "Downloaded"], ["x1owr0LEc3M", false, "Fail"], ["xHBUIt-airA", true, "Downloaded"], ["xP_XUyBwucQ", false, "Fail"], ["xkHEVAO46Z0", true, "Downloaded"], ["yBR39Ar6rCg", true, "Downloaded"], ["yIDi18JlgsQ", true, "Downloaded"], ["yKfVVj2rQVU", false, "Fail"], ["yNlBac0ZMJg", true, "Downloaded"], ["yXGu3dfnhck", true, "Downloaded"], ["yZ9dcxJzgyI", true, "Downloaded"], ["yj0pNXcTK0k", true, "Downloaded"], ["yvZPHJu3kb0", true, "Downloaded"], ["yz-uNJgIhk4", true, "Downloaded"], ["zLXhBdIX7lE", false, "Fail"], ["zNL3kn3UBmg", true, "Downloaded"], ["zfqS-wCJSsw", true, "Downloaded"]]

I've been trying to download FineGYM dataset, and I've found a lot of failures. I found that these videos are no longer available on YouTube, what should I do to get these videos?

**Comment by zhaoyue-zephyrus** [comment]
Hey @xxtars ,

 Thank you for your interests in our dataset. Can you try the new UT Box link below: https://utexas.box.com/s/oq2ce7i1mdgoihdwy9o7moolxzxsib42? Since I no longer have access to the CUHK OneDrive, I have migrated the data link to the new position. Hope this will help.

Best,
Yue
