### ISSUE TITLE
Release of raw videos

### ISSUE THREAD

**Issue by KevinQian97** [SDOlivia/FineGym#2]
Hi! I am really interested in the dataset u created.
I found in the current repo u only provide the extracted feature pickles. 
Do you have the attention to release relevant videos in the near future? (i.e. 1 month)
Thanks!

**Comment by zhaoyue-zephyrus** [comment]
Please see Q1 in the FAQs section in our [homepage](https://sdolivia.github.io/FineGym/).

**Comment by malldimi1** [comment]
Hi, thank you for your work.

I am really interested in your dataset but some of the youtube videos are unavailable and there doesn't seem to be a response on the relevant Google form about requesting video data (on your homepage). Is there any plan to make the missing data availiable?

Thank you again!
